# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
fr:
  languageCode: fr-ca
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/fr

# Uncomment the lines below to configure your website in a second language.
en:
 languageCode: en-us
 contentDir: content/en
 title: MEDomics UdeS Lab
 params:
    description: MEDomics UdeS Lab Website
 menu:
    main:
      - name: Tour
        url: tour
        weight: 10
      - name: News
        url: post
        weight: 20
      - name: People
        url: people
        weight: 30
      - name: Events
        url: event
        weight: 40
      - name: Publications
        url: publication
        weight: 50
      - name: Contact
        url: contact
        weight: 60

