# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
fr:
  languageCode: fr-ca
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/fr

# Uncomment the lines below to configure your website in a second language.
en:
 languageCode: en-us
 contentDir: content/en
 title: MEDomics UdeS Lab
 params:
    description: MEDomics UdeS Lab Website
 menu:
    main:
    - name: About
      url: about
      weight: 10
    - name: Courses
      url: courses
      weight: 15
    - name: News
      url: post
      weight: 20
    - name: Team
      url: team
      weight: 30
    - name: Projects
      url: projets
      weight: 40
    - name: Publications
      url: publications
      weight: 50
    - name: Contact
      url: contact
      weight: 60

